from __future__ import annotations

from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent
SOURCE_ENV_CANDIDATES = (
    PROJECT_DIR / ".env.release",
    PROJECT_DIR / ".env",
)
RELEASE_DIR = PROJECT_DIR / "release"
OUTPUT_ENV_PATH = RELEASE_DIR / ".env.runtime"
APP_VERSION = "2.1.1"
REQUIRED_KEYS = (
    "GEMINI_API_KEY",
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
)
ALLOWED_RUNTIME_KEYS = (
    "GEMINI_API_KEY",
    "NOVA_AI_MODEL",
    "GEMINI_CHAT_MODEL",
    "GEMINI_SOLVE_MODEL",
    "GEMINI_TYPING_MODEL",
    "GEMINI_TYPING_THINKING_LEVEL",
    "GEMINI_RETRY_COUNT",
    "GEMINI_RETRY_BACKOFF_SECONDS",
    "NOVA_AI_GEMINI_RETRY_COUNT",
    "NOVA_AI_GEMINI_RETRY_BACKOFF_SECONDS",
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
    "FIREBASE_PROJECT_ID",
    "NOVA_WEB_BASE_URL",
    "NOVA_USAGE_API_BASE_URL",
    "NOVA_APP_BASE_URL",
    "NEXT_PUBLIC_APP_URL",
    "NOVA_APP_VERSION",
    "NOVA_UPDATE_CHECK_ENABLED",
    "NOVA_UPDATE_MANIFEST_URL",
    "NOVA_UPDATE_DOWNLOAD_URL",
    "NOVA_UPDATE_MESSAGE",
    "NOVA_LATEST_VERSION",
    "NOVA_STARTUP_PREFLIGHT",
)


def parse_env_file(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        normalized_key = key.strip().lstrip("\ufeff")
        normalized_value = value.strip().strip('"').strip("'")
        if normalized_key:
            values[normalized_key] = normalized_value
    return values


def _resolve_source_env_path() -> Path | None:
    for candidate in SOURCE_ENV_CANDIDATES:
        if candidate.exists():
            return candidate
    return None


def _build_runtime_values(values: dict[str, str]) -> dict[str, str]:
    runtime_values: dict[str, str] = {}
    for key in ALLOWED_RUNTIME_KEYS:
        value = str(values.get(key, "")).strip()
        if value:
            runtime_values[key] = value

    runtime_values.setdefault("NOVA_APP_VERSION", APP_VERSION)
    runtime_values.setdefault("NOVA_STARTUP_PREFLIGHT", "1")
    runtime_values.setdefault("NOVA_WEB_BASE_URL", "https://www.nova-ai.work")
    runtime_values.setdefault("NEXT_PUBLIC_APP_URL", runtime_values["NOVA_WEB_BASE_URL"])
    return runtime_values


def _serialize_env(values: dict[str, str]) -> str:
    ordered_lines = [
        "# Auto-generated by prepare_release_runtime.py",
        "# Only runtime-safe keys required by the installed desktop app are included.",
        "",
    ]
    for key, value in values.items():
        ordered_lines.append(f"{key}={value}")
    ordered_lines.append("")
    return "\n".join(ordered_lines)


def main() -> int:
    source_env_path = _resolve_source_env_path()
    if source_env_path is None:
        candidate_names = ", ".join(path.name for path in SOURCE_ENV_CANDIDATES)
        print(f"[release] 배포용 원본 설정 파일이 없습니다: {candidate_names}")
        return 1

    text = source_env_path.read_text(encoding="utf-8-sig")
    values = parse_env_file(text)
    missing = [key for key in REQUIRED_KEYS if not values.get(key, "").strip()]
    if missing:
        print(f"[release] {source_env_path.name}에서 필수 값이 누락되었습니다:")
        for key in missing:
            print(f"  - {key}")
        return 1

    runtime_values = _build_runtime_values(values)
    RELEASE_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_ENV_PATH.write_text(_serialize_env(runtime_values), encoding="utf-8")
    print(f"[release] 배포용 런타임 설정 생성 완료: {OUTPUT_ENV_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
